name: TAMU Job Scraper

on:
  schedule:
    - cron: '0 18 * * *'  # every day at 18:00 UTC (adjust as needed)
  workflow_dispatch:     # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run scraper
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python job_scraper.py
        
      - name: Upload debug screenshot
        uses: actions/upload-artifact@v4
        with:
            name: page-debug-screenshot
            path: page_debug.png
# Example snippet to add in your workflow YAML file

      - name: Run job scraper
        run: python job_scraper.py
        continue-on-error: true  # <- don't stop the workflow if this fails

      - name: Upload screenshots
        if: always()  # <- always upload, even if previous step failed
        uses: actions/upload-artifact@4
        with:
          name: debug-screenshots
          path: screenshots/



