name: Daily Job Scraper

on:
  schedule:
    - cron: '0 18 * * *'  # Runs every day at 6 PM UTC
  workflow_dispatch:      # Allows you to trigger it manually

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4 pandas

    - name: Run Job Scraper
      run: python job_scraper.py
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
